main: VecLinkClientSpigot.FalconMainSpigot
version: 0.0
name: VecLinkClient
softdepend:
  - PlaceholderAPI
commands:
  veclink:
    description: parent command.
    usage: /<command> []

permissions:
  veclink.admin:
    default: op
    description: veclink admin.