#Enabling this module will allow you to format and sync chats with other servers.
#If you are looking for chat groups then you can find it in the veclinkServer's config.
#Setup Chat groups to only allow members with the permission "veclink.chatgroup.<groupName>" to send and receive messages from other members.
#Usefull Commands:-
#/veclink chatGroup <groupName> <message> {send messages to the mentioned group}
#/veclink muteChat <groupName> {ignore messages from the mentioned group}
chat-module:
  #Enable this module.
  enabled: true
  #Define the chat format for local chats. (keep it blank if you have some other plugin handling the chat format)
  regular-format: '[%luckperms_prefix%][player]: [message]'
  #Enabling this will allow you to sync chats with other servers.
  sync-chats: true
  #Define the chat format for outgoing chats.
  outgoing-format: '[%luckperms_prefix%][player]: [message]'
  #Set this to true will echo the message back to this server. keep it false unless you want duplicate messages.
  echo: false
  #Add the servers to which you want to sync chats with. You can also use groups by following the "group:<groupName>" syntax.
  target-servers:
    - 'clientTest'
    - 'TestClient1'
    - 'group:default'
    -
#You can use these placeholders anywhere in the config. This also includes the math expansion for easy mathematical calculations.
#goto this webpage to know about the format of math placeholder https://github.com/Andre601/Math-Expansion
#list of available placeholder:
# %fcln_onlineStatus_<client-id>%
# %fcln_onlineStatusBoolean_<client-id>%
# %fcln_playerCount_<client-id>%

#This is some additional configurations for each placeholder.
placeholder-config:
  onlineStatus:
    true: "<green>ONLINE"
    false: "<red>OFFLINE"
  clientStatus:
    true: "<green>CONNECTED"
    false: "<red>NOT CONNECTED"
