bot_token: 'test'
guild_id: '980140597115514980'

verification_channel_id: ''
on_verify_success:
  - 'addRole <roleID> %user_id%'
  - 'changeNick %user_id% %user_name% IGN: %player_name%'
on_verify_fail:
  - 'remRole <roleID> %user_id%'


